unstable_features = true

blank_lines_upper_bound = 1

wrap_comments = true

condense_wildcard_suffixes = true

error_on_line_overflow = true
error_on_unformatted = true

format_macro_matchers = true
format_strings = true

hex_literal_case = "Upper"

imports_layout = "HorizontalVertical"
imports_granularity = "One"

newline_style = "Unix"

normalize_comments = true
normalize_doc_attributes = true

overflow_delimited_expr = true

trailing_semicolon = false

use_field_init_shorthand = true
use_try_shorthand = true
