on:
  release:
    types: [created]

name: Release

jobs:
  release:
    name: Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: x86_64-pc-windows-gnu
          ARCHIVE_TYPES: zip
